---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 4407584182-NUALPnzcdNQ6MPyRA78VgWl8e91jNObn1rZRsAQ
:access_token_secret: 5tAmibW1B9p5qE6EDDMN5iatioLrWrdUQ2fXrDBNg7T7C
